# PS4 config file
joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0  # [ms]

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1  # ls vertical
    scale_linear:
      x: 0.5  # [m/s]
    scale_linear_turbo:
      x: 1.0  # [m/s]

    axis_angular:
      yaw: 3  # rs horizontal
    scale_angular:
      yaw: 0.5  # [deg/s]
    scale_angular_turbo:
      yaw: 1.0  # [deg/s]

    enable_button: 4 # TODO find
    enable_turbo_button: 5  # TODO find

    require_enable_button: true  # explicit, not necessary